services:
  redis:
    image: redis:alpine
    container_name: transtrack-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  api:
    build: .
    container_name: transtrack-yawn-api
    ports:
      - "8000:8000"
    volumes:
      - ./model_weights:/app/model_weights
    environment:
      - DEVICE=cpu
      - MODEL_VARIANT=vj
      - OMP_NUM_THREADS=2
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    restart: unless-stopped

  worker:
    build: .
    # No static container_name so we can scale > 1
    volumes:
      - ./model_weights:/app/model_weights
    command: ["rq", "worker", "-u", "redis://redis:6379/0", "yawn_tasks"]
    environment:
      - DEVICE=cpu
      - MODEL_VARIANT=vj
      - OMP_NUM_THREADS=2
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    restart: unless-stopped
